name: Execute automated checks
on:
  - push
jobs:
# https://github.com/golangci/golangci-lint-action#how-to-use
  go-lint:
    name: Lint go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - name: Lint go code with golangci-lint
        uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018 # renovate: tag=v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.61.0
  go-test:
    name: Verify go tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - name: Setup golang
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # renovate: tag=v2
        with:
          go-version: v1.61.0
      - name: Print go version
        run: go version
      - name: Execute go tests 
        run: go test -v ./...
